name: speakeasy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  path_provider: ^2.1.2
  http: ^1.4.0
  flutter_tts: ^4.2.2
  permission_handler: ^12.0.0+1
  translator: ^1.0.3+1
  share_plus: ^11.0.0
  lottie: ^3.3.1
  introduction_screen: ^3.1.5
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  connectivity_plus: ^5.0.2
  audio_waveforms: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  clipboard: ^0.1.3
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.0
  google_mobile_ads: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/splash_travel.json
    - assets/plane.json
    - assets/listening.json
    - assets/globe.json
    - assets/mic.json
    - assets/mic.svg
    - assets/globe.svg
    - assets/travel.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf