// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5CByDOyckfPAOTbyV70q40l6AijnTpE',
    appId: '1:441440116674:web:1ec8f0db85c07df1dec05b',
    messagingSenderId: '441440116674',
    projectId: 'speakeasy-afdaa',
    authDomain: 'speakeasy-afdaa.firebaseapp.com',
    storageBucket: 'speakeasy-afdaa.firebasestorage.app',
    measurementId: 'G-3DRLDR0WR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApl-qK7C4frpFY4qh7eAEn2rQ1IkpjsK0',
    appId: '1:441440116674:android:e091befcbe051a7fdec05b',
    messagingSenderId: '441440116674',
    projectId: 'speakeasy-afdaa',
    storageBucket: 'speakeasy-afdaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7B5FJAKQZ6AILr5IPMr6Q3ty8rbi42jA',
    appId: '1:441440116674:ios:5360a1a2cc4201b8dec05b',
    messagingSenderId: '441440116674',
    projectId: 'speakeasy-afdaa',
    storageBucket: 'speakeasy-afdaa.firebasestorage.app',
    iosBundleId: 'com.slns.speakeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7B5FJAKQZ6AILr5IPMr6Q3ty8rbi42jA',
    appId: '1:441440116674:ios:5360a1a2cc4201b8dec05b',
    messagingSenderId: '441440116674',
    projectId: 'speakeasy-afdaa',
    storageBucket: 'speakeasy-afdaa.firebasestorage.app',
    iosBundleId: 'com.slns.speakeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj5CByDOyckfPAOTbyV70q40l6AijnTpE',
    appId: '1:441440116674:web:e28ad1eb74b819b4dec05b',
    messagingSenderId: '441440116674',
    projectId: 'speakeasy-afdaa',
    authDomain: 'speakeasy-afdaa.firebaseapp.com',
    storageBucket: 'speakeasy-afdaa.firebasestorage.app',
    measurementId: 'G-L8LLQ8LEJY',
  );
}
